
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Mar 16 22:28:35 MSK 2022
//----------------------------------------------------

package o_project_compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 29;
  public static final int READ = 24;
  public static final int CONTINUE = 22;
  public static final int ELSE = 30;
  public static final int CLASS = 6;
  public static final int IDENT = 4;
  public static final int OR = 28;
  public static final int RPAREN = 17;
  public static final int RBRACE = 7;
  public static final int INT = 10;
  public static final int WHILE = 20;
  public static final int CHAR = 12;
  public static final int SEMI = 5;
  public static final int RETURN = 23;
  public static final int ERROR = 32;
  public static final int IF = 19;
  public static final int LBRACKET = 13;
  public static final int LPAREN = 16;
  public static final int LBRACE = 3;
  public static final int THIS = 33;
  public static final int RBRACKET = 14;
  public static final int PROGRAM = 2;
  public static final int DO = 31;
  public static final int COMMA = 8;
  public static final int EOF = 0;
  public static final int BREAK = 21;
  public static final int DOT = 26;
  public static final int PRINT = 25;
  public static final int error = 1;
  public static final int ASSIGN = 9;
  public static final int NEW = 27;
  public static final int BOOL = 11;
  public static final int EXTENDS = 15;
  public static final int VOID = 18;
}

